### ISSUE TITLE
路径问题请教

### ISSUE THREAD

**Issue by aiadaniel** [mafei198/gos#4]
1.您那golang的版本是多少，我本地1.11.4
2.我下载的路径：F:\gospace\src\github.com\mafei198\gos
但导入到idea时，依旧显示找不到包，费解（截图https://imgchr.com/i/ZJc6nH 不知道您能不能看到截图，显示路径还是需要加上src，才能对应得上）

**Comment by mafei198** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    1.我的golang版本是最新的2.目前是使用的go mod 进行依赖管理，在项目根目录执行make setup依赖管理：go module (https://blog.golang.org/using-go-modules)
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                mafei.198
                            
                    
                        
                            
                                    mafei.198@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年07月2日 18:03，aiadaniel<notifications@github.com> 写道： 


1.您那golang的版本是多少，我本地1.11.4

2.我下载的路径：F:\gospace\src\github.com\mafei198\gos

但导入到idea时，依旧显示找不到包，费解（截图https://imgchr.com/i/ZJc6nH） 不知道您能不能看到截图，显示路径还是需要加上src，才能对应得上



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
